name: easylist
description: Easylist Project ESTG

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^0.2.5
  firebase_auth: ^0.5.19
  google_sign_in: ^3.0.5
  cloud_firestore: ^0.7.4
  cupertino_icons: ^0.1.2
  barcode_scan: ^0.0.5
  font_awesome_flutter: ^8.0.1
  validate: ^1.6.1
  intro_slider: ^1.0.6
  firebase_storage: ^1.0.2
  intl: ^0.15.7
  fluttertoast: ^2.0.7
  url_launcher: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/list.jpg
   - assets/images/straw1.jpg
   - assets/images/straw3.jpg
   - assets/images/assignment.png
   - assets/images/barcodescan.png
   - assets/images/facebook_logo.png
   - assets/images/share.png
   - assets/images/todo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: bpp
      fonts:
        - asset: assets/fonts/BPP.ttf
    - family: lato
      fonts:
        - asset: assets/fonts/lato.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
